defaults: &defaults
  base_url: "https://komin.malmo.se/"
  assets_url_base: "//assets.malmo.se/internal/v4-staging/"
  session_time: 60 # minutes

development: &development
  <<: *defaults
  assets_url_base: "//assets.malmo.se/internal/v4/"
  cache_ttl: 1
  max_age: 0
  title_suffix: "Vagnar (utveckling)"
  session_time: 1440
  stub_auth: true

test:
  <<: *defaults
  assets_url_base: "//assets.malmo.se/internal/v4-staging/"
  cache_ttl: 43200
  max_age: 14400
  title_suffix: "Vagnar (test)"

production: &production
  <<: *defaults
  assets_url_base: "//assets.malmo.se/internal/v4/"
  cache_ttl: 43200
  max_age: 14400
  title_suffix: "Vagnar"
