default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_swedish_ci
  host: localhost
  pool: 20
  username: vagnar
  password: <PW>
  database: vagnar

development:
  <<: *default

test: &test
  <<: *default
  database: vagnar_test
  password: <PW>

production:
  <<: *default
  password: <PW>
