default: &defaults
  ldap:
    host: ad.example.org
    port: 636
    system_username: <ldap system username>
    system_password: <ldap system password>
    basedn: <base dn for users>
    base_group: <base for application group accounts>
    groups:
      - ldap_name: <group name for sysadmin>
        name: admin
  saml: &saml
    idp_metadata: 'https://example.org/saml/metadata'
    idp_authn_context: <IDP authn context>
    idp_sso_target_url: 'https://example.org/saml/auth'
    idp_slo_target_url: 'https://example.org/saml/slo'
    idp_cert: '-----BEGIN CERTIFICATE-----
<wrapped cert lines>
  -----END CERTIFICATE-----'
    idp_cert_fingerprint: 'xx:xx'

development:
  <<: *defaults
  secret_key_base: # Run $ rails secret to generate keys

test:
  <<: *defaults
  secret_key_base: # Run $ rails secret to generate keys

production:
  secret_key_base: # Run $ rails secret to generate keys
